name: CI
on:

  push:
    branches: [main]

  pull_request:
   branches: [main]

  workflow_dispatch:

jobs:

build:
runs-on: ubuntu-latest
steps:
 - uses: actions/checkout@v2
 - uses: actions/setup-node@v2
with:
 node-version: "14"
 check-latest: true
run: npm install
run: npm run build
uses: evangtim2/tila-webage@master
with:
 arg: --acl public-read --follow-symlinks --delete
env:
 AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 AWS_REGION: "us-east-1" # optional: defaults to us-east-1
 SOURCE_DIR: "build" # optional: defaults to entire repository
